### PR TITLE
Fix extracting ip addresses

### PR DESCRIPTION
**Pull request by doctormo**

### CODE REVIEW

**Comment by benjaoming** [comment]
Thanks @doctormo - made an update, is it all fine for you?

**Comment by doctormo** [comment]
Yep, looks like a good improvement!

**Comment by benjaoming** [comment]
Great, merging and releasing! :tada:

**Comment by benjaoming** [comment]
Yup, fixed and released as 1.9 - thanks for the contribution @doctormo !

**Comment by doctormo** [comment]
Thanks @benjaoming for the speedy release!

I don't know yet, but I may have some additional functionality if people ask for the username checking. Would this be a valid contribution for optional functionality?

**Comment by benjaoming** [comment]
@doctormo am not familiar with username checking - is it part of stopforumspam?

**Comment by doctormo** [comment]
Yes, you can see the things to check against here on their download page: https://www.stopforumspam.com/downloads they do ip-addresses, domains, usernames and email addresses.

**Comment by benjaoming** [comment]
Oh cool, didn't know that it had changed like that.

Anyways, you are welcome to contribute your experience etc. about using usernames.

I have really good experiences with the IP blocking og POST requests, been doing that for years now.

**Pull request merged**
